### ISSUE TITLE
socket.herror: [Errno 1] Unknown host

### ISSUE THREAD

**Issue by CNMan** [ip2location/ip2trace-python#2]
```python
[root@localhost ]# ip2trace -p 116.122.36.54 -d IP-COUNTRY-REGION-CITY-ISP.BIN -t 30                               
Traceback (most recent call last):
  File "/usr/local/bin/ip2trace", line 11, in <module>
    load_entry_point('IP2Trace==2.1.7', 'console_scripts', 'ip2trace')()
  File "/usr/local/lib/python3.6/site-packages/ip2trace.py", line 482, in main
    traceroute(destination_server, database, max_hops, output, all)
  File "/usr/local/lib/python3.6/site-packages/ip2trace.py", line 148, in traceroute
    t = Traceroute(destination_server, database, ttl, output, all)
  File "/usr/local/lib/python3.6/site-packages/ip2trace.py", line 174, in __init__
    self.destination_domain_name = ip_to_domain_name(destination_server)
  File "/usr/local/lib/python3.6/site-packages/ip2trace.py", line 97, in ip_to_domain_name
    return socket.gethostbyaddr(hostname)
socket.herror: [Errno 1] Unknown host
[root@localhost ]# 
```

**Comment by ip2location-com** [comment]
Hi CNMan,

Thanks for the feedback. We have fixed the issue and released a new version in PyPI. You can now update to the latest version.
